"""
Sync implementation package.

Internal structure for sync automation. Use the public API via
`from src.scripts.automation.sync import ...` (sync.py re-exports).
"""

from .settings import (
    DATA_DIR,
    get_sync_data_dir,
    LIKED_SONGS_PLAYLIST_ID,
    SPOTIFY_API_PAGINATION_LIMIT,
    SPOTIFY_API_MAX_TRACKS_PER_REQUEST,
    API_RATE_LIMIT_MAX_RETRIES,
    MIN_TRACK_ID_LENGTH,
    KEEP_MONTHLY_MONTHS,
    OWNER_NAME,
    BASE_PREFIX,
    ENABLE_MONTHLY,
    ENABLE_MOST_PLAYED,
    ENABLE_DISCOVERY,
    PREFIX_MONTHLY,
    PREFIX_GENRE_MONTHLY,
    PREFIX_YEARLY,
    PREFIX_GENRE_MASTER,
    PREFIX_MOST_PLAYED,
    PREFIX_DISCOVERY,
    MONTHLY_NAME_TEMPLATE,
    GENRE_NAME_TEMPLATE,
    GENRE_MONTHLY_TEMPLATE,
    DATE_FORMAT,
    SEPARATOR_MONTH,
    SEPARATOR_PREFIX,
    CAPITALIZATION,
    MONTH_NAMES_SHORT,
    MONTH_NAMES_MEDIUM,
    MONTH_NAMES,
    DESCRIPTION_TEMPLATE,
    DESCRIPTION_TOP_GENRES,
    SPOTIFY_MAX_DESCRIPTION_LENGTH,
    SPOTIFY_MAX_GENRE_TAGS,
    SPOTIFY_MAX_GENRE_TAG_LENGTH,
    MOOD_MAX_TAGS,
    DEFAULT_DISCOVERY_TRACK_LIMIT,
)
from .logger import log, verbose_log, log_step_banner, timed_step, set_verbose, get_log_buffer
from .api import api_call, get_spotify_client, _chunked
from .catalog import (
    get_existing_playlists,
    get_playlist_tracks,
    get_user_info,
    _invalidate_playlist_cache,
    _load_genre_data,
    _playlist_cache,
    _playlist_tracks_cache,
)
from .tracks import (
    _to_uri,
    _uri_to_track_id,
    _get_preview_urls_for_tracks,
    _get_audio_features_for_tracks,
    _parse_genres,
    _get_all_track_genres,
    _get_primary_artist_genres,
)
from .descriptions import (
    _get_genres_from_track_uris,
    _get_genre_emoji,
    _format_genre_tags,
    _add_genre_tags_to_description,
    _update_playlist_description_with_genres,
)
from .mood import run_mood_inference_on_sync
from .genre_compute import compute_track_genres_incremental
from .workflow import sync_full_library, sync_export_data
from .renames import (
    rename_playlists_with_old_prefixes,
    fix_incorrectly_named_yearly_genre_playlists,
)
from .history import (
    get_most_played_tracks,
    get_time_based_tracks,
    get_repeat_tracks,
    get_discovery_tracks,
)

__all__ = [
    "DATA_DIR",
    "get_sync_data_dir",
    "LIKED_SONGS_PLAYLIST_ID",
    "SPOTIFY_API_PAGINATION_LIMIT",
    "SPOTIFY_API_MAX_TRACKS_PER_REQUEST",
    "API_RATE_LIMIT_MAX_RETRIES",
    "MIN_TRACK_ID_LENGTH",
    "KEEP_MONTHLY_MONTHS",
    "OWNER_NAME",
    "BASE_PREFIX",
    "ENABLE_MONTHLY",
    "ENABLE_MOST_PLAYED",
    "ENABLE_DISCOVERY",
    "PREFIX_MONTHLY",
    "PREFIX_GENRE_MONTHLY",
    "PREFIX_YEARLY",
    "PREFIX_GENRE_MASTER",
    "PREFIX_MOST_PLAYED",
    "PREFIX_DISCOVERY",
    "MONTHLY_NAME_TEMPLATE",
    "GENRE_NAME_TEMPLATE",
    "GENRE_MONTHLY_TEMPLATE",
    "DATE_FORMAT",
    "SEPARATOR_MONTH",
    "SEPARATOR_PREFIX",
    "CAPITALIZATION",
    "MONTH_NAMES_SHORT",
    "MONTH_NAMES_MEDIUM",
    "MONTH_NAMES",
    "DESCRIPTION_TEMPLATE",
    "DESCRIPTION_TOP_GENRES",
    "SPOTIFY_MAX_DESCRIPTION_LENGTH",
    "SPOTIFY_MAX_GENRE_TAGS",
    "SPOTIFY_MAX_GENRE_TAG_LENGTH",
    "MOOD_MAX_TAGS",
    "DEFAULT_DISCOVERY_TRACK_LIMIT",
    "log",
    "verbose_log",
    "log_step_banner",
    "timed_step",
    "set_verbose",
    "get_log_buffer",
    "api_call",
    "get_spotify_client",
    "_chunked",
    "get_existing_playlists",
    "get_playlist_tracks",
    "get_user_info",
    "_invalidate_playlist_cache",
    "_load_genre_data",
    "_playlist_cache",
    "_playlist_tracks_cache",
    "_to_uri",
    "_uri_to_track_id",
    "_get_preview_urls_for_tracks",
    "_get_audio_features_for_tracks",
    "_parse_genres",
    "_get_all_track_genres",
    "_get_primary_artist_genres",
    "_get_genres_from_track_uris",
    "_get_genre_emoji",
    "_format_genre_tags",
    "_add_genre_tags_to_description",
    "_update_playlist_description_with_genres",
    "run_mood_inference_on_sync",
    "compute_track_genres_incremental",
    "sync_full_library",
    "sync_export_data",
    "rename_playlists_with_old_prefixes",
    "fix_incorrectly_named_yearly_genre_playlists",
    "get_most_played_tracks",
    "get_time_based_tracks",
    "get_repeat_tracks",
    "get_discovery_tracks",
]
