"""
Sync settings: paths, constants, and env overrides.

Single source for sync-specific configuration. Re-exports from config.
Project root and data dir come from config (which uses project_path so data
lives under SPOTIM8 unless SPOTIM8_DATA_DIR / DATA_DIR env is set).
"""

from pathlib import Path

from src.scripts.automation import config

# Project root and data dir: from config (canonical; data under SPOTIM8)
PROJECT_ROOT = config.PROJECT_ROOT
DATA_DIR = config.DATA_DIR

# Re-export from config
LIKED_SONGS_PLAYLIST_ID = config.LIKED_SONGS_PLAYLIST_ID
SPOTIFY_API_PAGINATION_LIMIT = config.SPOTIFY_API_PAGINATION_LIMIT
SPOTIFY_API_MAX_TRACKS_PER_REQUEST = getattr(config, "SPOTIFY_API_MAX_TRACKS_PER_REQUEST", 100)
API_RATE_LIMIT_MAX_RETRIES = config.API_RATE_LIMIT_MAX_RETRIES
MIN_TRACK_ID_LENGTH = config.MIN_TRACK_ID_LENGTH
KEEP_MONTHLY_MONTHS = config.KEEP_MONTHLY_MONTHS
OWNER_NAME = config.OWNER_NAME
BASE_PREFIX = config.BASE_PREFIX
ENABLE_MONTHLY = config.ENABLE_MONTHLY
ENABLE_MOST_PLAYED = config.ENABLE_MOST_PLAYED
ENABLE_DISCOVERY = config.ENABLE_DISCOVERY
PREFIX_MONTHLY = config.PREFIX_MONTHLY
PREFIX_GENRE_MONTHLY = config.PREFIX_GENRE_MONTHLY
PREFIX_YEARLY = config.PREFIX_YEARLY
PREFIX_GENRE_MASTER = config.PREFIX_GENRE_MASTER
PREFIX_MOST_PLAYED = config.PREFIX_MOST_PLAYED
PREFIX_DISCOVERY = config.PREFIX_DISCOVERY
MONTHLY_NAME_TEMPLATE = config.MONTHLY_NAME_TEMPLATE
GENRE_NAME_TEMPLATE = config.GENRE_NAME_TEMPLATE
GENRE_MONTHLY_TEMPLATE = config.GENRE_MONTHLY_TEMPLATE
DATE_FORMAT = config.DATE_FORMAT
SEPARATOR_MONTH = config.SEPARATOR_MONTH
SEPARATOR_PREFIX = config.SEPARATOR_PREFIX
CAPITALIZATION = config.CAPITALIZATION
MONTH_NAMES_SHORT = config.MONTH_NAMES_SHORT
MONTH_NAMES_MEDIUM = config.MONTH_NAMES_MEDIUM
MONTH_NAMES = config.MONTH_NAMES
DESCRIPTION_TEMPLATE = config.DESCRIPTION_TEMPLATE
DESCRIPTION_TOP_GENRES = config.DESCRIPTION_TOP_GENRES
SPOTIFY_MAX_DESCRIPTION_LENGTH = config.SPOTIFY_MAX_DESCRIPTION_LENGTH
SPOTIFY_MAX_GENRE_TAGS = config.SPOTIFY_MAX_GENRE_TAGS
SPOTIFY_MAX_GENRE_TAG_LENGTH = config.SPOTIFY_MAX_GENRE_TAG_LENGTH
MOOD_MAX_TAGS = config.MOOD_MAX_TAGS
DEFAULT_DISCOVERY_TRACK_LIMIT = config.DEFAULT_DISCOVERY_TRACK_LIMIT
PARALLEL_MIN_TRACKS = getattr(config, "PARALLEL_MIN_TRACKS", 50)


def get_sync_data_dir() -> Path:
    """
    Return the data directory used by sync (where playlists.parquet etc. live).
    Uses DATA_DIR (canonical: under SPOTIM8 unless env overrides).
    """
    return DATA_DIR
